#!/usr/bin/env php
<?php
use Symfony\Component\Console\Input\ArgvInput;
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$status = $app->handleCommand(new ArgvInput);
exit($status);
